/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package EG3;

public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Eg3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=613617a8805712f5847d5884a6b593ec (do not edit this line) */
