/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package EG3;

public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Eg3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=94eec8a5a1991446927597c9ff55895c (do not edit this line) */
