/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package EG2;

import EG2.SimpleNode;

public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a8a15f13683db37baf08f6ea6830546 (do not edit this line) */
