/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package EG2;

import EG2.SimpleNode;

public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8012f2552be0c02cf5c619af87db6dc7 (do not edit this line) */
