/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package EG2;

import EG2.SimpleNode;

public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Eg2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f9848d8ae38772f3497290eb8cabccd (do not edit this line) */
